### ISSUE TITLE
Read specs file

### ISSUE THREAD

**Issue by pabloriutort** [pabloriutort/DRAM-Simulator#4]
Use YAML library for Python to read .yml file to specify the specs of a DRAM memory.

Example:
```
dram:
    capacity: 1
    chips:
        number: 8
        banks: 1
        rows: 1
        columns: 1
        capacity: 524
    times:
        rp: 1
        rcd: 1
        cl: 1
```
